// Dicionário iso3 → { name, capital, continent }. Cobre ~200 países.
// Ampliar conforme necessário. Entradas ausentes caem no fallback "—".

export type CountryMeta = { name: string; capital: string; continent: string };

export const COUNTRY_META: Record<string, CountryMeta> = {
  AFG: { name: "Afeganistão",              capital: "Cabul",                continent: "Ásia" },
  ALB: { name: "Albânia",                  capital: "Tirana",               continent: "Europa" },
  DZA: { name: "Argélia",                  capital: "Argel",                continent: "África" },
  AND: { name: "Andorra",                  capital: "Andorra-a-Velha",      continent: "Europa" },
  AGO: { name: "Angola",                   capital: "Luanda",               continent: "África" },
  ARG: { name: "Argentina",               capital: "Buenos Aires",          continent: "América do Sul" },
  ARM: { name: "Armênia",                  capital: "Erevan",               continent: "Ásia" },
  AUS: { name: "Austrália",               capital: "Camberra",              continent: "Oceania" },
  AUT: { name: "Áustria",                 capital: "Viena",                 continent: "Europa" },
  AZE: { name: "Azerbaijão",              capital: "Baku",                  continent: "Ásia" },
  BHS: { name: "Bahamas",                 capital: "Nassau",                continent: "América do Norte" },
  BHR: { name: "Bahrein",                 capital: "Manama",               continent: "Ásia" },
  BGD: { name: "Bangladesh",              capital: "Daca",                  continent: "Ásia" },
  BRB: { name: "Barbados",               capital: "Bridgetown",             continent: "América do Norte" },
  BLR: { name: "Bielorrússia",            capital: "Minsk",                continent: "Europa" },
  BEL: { name: "Bélgica",                capital: "Bruxelas",              continent: "Europa" },
  BLZ: { name: "Belize",                  capital: "Belmopan",             continent: "América do Norte" },
  BEN: { name: "Benin",                   capital: "Porto Novo",            continent: "África" },
  BTN: { name: "Butão",                   capital: "Timbu",                continent: "Ásia" },
  BOL: { name: "Bolívia",                capital: "Sucre",                  continent: "América do Sul" },
  BIH: { name: "Bósnia e Herzegovina",   capital: "Sarajevo",              continent: "Europa" },
  BWA: { name: "Botsuana",               capital: "Gaborone",              continent: "África" },
  BRA: { name: "Brasil",                  capital: "Brasília",             continent: "América do Sul" },
  BRN: { name: "Brunei",                  capital: "Bandar Seri Begawan",  continent: "Ásia" },
  BGR: { name: "Bulgária",               capital: "Sófia",                 continent: "Europa" },
  BFA: { name: "Burkina Faso",           capital: "Uagadugu",              continent: "África" },
  BDI: { name: "Burundi",                capital: "Gitega",                continent: "África" },
  KHM: { name: "Camboja",               capital: "Phnom Penh",             continent: "Ásia" },
  CMR: { name: "Camarões",              capital: "Iaundé",                  continent: "África" },
  CAN: { name: "Canadá",                capital: "Ottawa",                  continent: "América do Norte" },
  CPV: { name: "Cabo Verde",             capital: "Praia",                 continent: "África" },
  CAF: { name: "República Centro-Africana", capital: "Bangui",             continent: "África" },
  TCD: { name: "Chade",                  capital: "N'Djamena",             continent: "África" },
  CHL: { name: "Chile",                  capital: "Santiago",              continent: "América do Sul" },
  CHN: { name: "China",                  capital: "Pequim",               continent: "Ásia" },
  COL: { name: "Colômbia",              capital: "Bogotá",                  continent: "América do Sul" },
  COM: { name: "Comores",               capital: "Moroni",                 continent: "África" },
  COG: { name: "Congo",                  capital: "Brazzaville",           continent: "África" },
  COD: { name: "Rep. Dem. do Congo",    capital: "Kinshasa",               continent: "África" },
  CRI: { name: "Costa Rica",            capital: "San José",               continent: "América do Norte" },
  CIV: { name: "Costa do Marfim",       capital: "Yamoussoukro",           continent: "África" },
  HRV: { name: "Croácia",              capital: "Zagreb",                   continent: "Europa" },
  CUB: { name: "Cuba",                  capital: "Havana",                 continent: "América do Norte" },
  CYP: { name: "Chipre",               capital: "Nicósia",                  continent: "Europa" },
  CZE: { name: "República Tcheca",      capital: "Praga",                  continent: "Europa" },
  DNK: { name: "Dinamarca",            capital: "Copenhague",               continent: "Europa" },
  DJI: { name: "Djibuti",              capital: "Djibuti",                  continent: "África" },
  DOM: { name: "República Dominicana", capital: "Santo Domingo",            continent: "América do Norte" },
  ECU: { name: "Equador",              capital: "Quito",                    continent: "América do Sul" },
  EGY: { name: "Egito",               capital: "Cairo",                     continent: "África" },
  SLV: { name: "El Salvador",         capital: "San Salvador",              continent: "América do Norte" },
  GNQ: { name: "Guiné Equatorial",    capital: "Malabo",                    continent: "África" },
  ERI: { name: "Eritreia",            capital: "Asmara",                    continent: "África" },
  EST: { name: "Estônia",             capital: "Tallinn",                   continent: "Europa" },
  SWZ: { name: "Essuatíni",           capital: "Mbabane",                   continent: "África" },
  ETH: { name: "Etiópia",            capital: "Adis Abeba",                 continent: "África" },
  FJI: { name: "Fiji",               capital: "Suva",                       continent: "Oceania" },
  FIN: { name: "Finlândia",          capital: "Helsinque",                  continent: "Europa" },
  FRA: { name: "França",             capital: "Paris",                      continent: "Europa" },
  GAB: { name: "Gabão",              capital: "Libreville",                 continent: "África" },
  GMB: { name: "Gâmbia",            capital: "Banjul",                      continent: "África" },
  GEO: { name: "Geórgia",           capital: "Tbilisi",                     continent: "Ásia" },
  DEU: { name: "Alemanha",          capital: "Berlim",                      continent: "Europa" },
  GHA: { name: "Gana",              capital: "Acra",                        continent: "África" },
  GRC: { name: "Grécia",            capital: "Atenas",                      continent: "Europa" },
  GTM: { name: "Guatemala",         capital: "Cidade da Guatemala",          continent: "América do Norte" },
  GIN: { name: "Guiné",             capital: "Conacri",                     continent: "África" },
  GNB: { name: "Guiné-Bissau",      capital: "Bissau",                     continent: "África" },
  GUY: { name: "Guiana",           capital: "Georgetown",                   continent: "América do Sul" },
  HTI: { name: "Haiti",            capital: "Porto Príncipe",               continent: "América do Norte" },
  HND: { name: "Honduras",         capital: "Tegucigalpa",                  continent: "América do Norte" },
  HUN: { name: "Hungria",          capital: "Budapeste",                    continent: "Europa" },
  ISL: { name: "Islândia",         capital: "Reykjavík",                   continent: "Europa" },
  IND: { name: "Índia",            capital: "Nova Déli",                    continent: "Ásia" },
  IDN: { name: "Indonésia",        capital: "Jacarta",                      continent: "Ásia" },
  IRN: { name: "Irã",              capital: "Teerã",                        continent: "Ásia" },
  IRQ: { name: "Iraque",           capital: "Bagdá",                        continent: "Ásia" },
  IRL: { name: "Irlanda",          capital: "Dublin",                       continent: "Europa" },
  ISR: { name: "Israel",           capital: "Jerusalém",                    continent: "Ásia" },
  ITA: { name: "Itália",           capital: "Roma",                         continent: "Europa" },
  JAM: { name: "Jamaica",          capital: "Kingston",                     continent: "América do Norte" },
  JPN: { name: "Japão",            capital: "Tóquio",                       continent: "Ásia" },
  JOR: { name: "Jordânia",         capital: "Amã",                          continent: "Ásia" },
  KAZ: { name: "Cazaquistão",      capital: "Astana",                       continent: "Ásia" },
  KEN: { name: "Quênia",           capital: "Nairóbi",                      continent: "África" },
  KIR: { name: "Quiribati",        capital: "Tarawa",                       continent: "Oceania" },
  PRK: { name: "Coreia do Norte",  capital: "Pyongyang",                    continent: "Ásia" },
  KOR: { name: "Coreia do Sul",    capital: "Seul",                         continent: "Ásia" },
  KWT: { name: "Kuwait",           capital: "Cidade do Kuwait",             continent: "Ásia" },
  KGZ: { name: "Quirguistão",      capital: "Bisqueque",                    continent: "Ásia" },
  LAO: { name: "Laos",             capital: "Vienciana",                    continent: "Ásia" },
  LVA: { name: "Letônia",          capital: "Riga",                         continent: "Europa" },
  LBN: { name: "Líbano",           capital: "Beirute",                      continent: "Ásia" },
  LSO: { name: "Lesoto",           capital: "Maseru",                       continent: "África" },
  LBR: { name: "Libéria",          capital: "Monróvia",                     continent: "África" },
  LBY: { name: "Líbia",            capital: "Trípoli",                      continent: "África" },
  LIE: { name: "Liechtenstein",    capital: "Vaduz",                        continent: "Europa" },
  LTU: { name: "Lituânia",         capital: "Vilnius",                      continent: "Europa" },
  LUX: { name: "Luxemburgo",       capital: "Luxemburgo",                   continent: "Europa" },
  MDG: { name: "Madagascar",       capital: "Antananarivo",                 continent: "África" },
  MWI: { name: "Malaui",           capital: "Lilongwe",                     continent: "África" },
  MYS: { name: "Malásia",          capital: "Kuala Lumpur",                 continent: "Ásia" },
  MDV: { name: "Maldivas",         capital: "Malé",                         continent: "Ásia" },
  MLI: { name: "Mali",             capital: "Bamako",                       continent: "África" },
  MLT: { name: "Malta",            capital: "Valeta",                       continent: "Europa" },
  MRT: { name: "Mauritânia",       capital: "Nouakchott",                   continent: "África" },
  MUS: { name: "Maurício",         capital: "Porto Luís",                   continent: "África" },
  MEX: { name: "México",           capital: "Cidade do México",             continent: "América do Norte" },
  MDA: { name: "Moldávia",         capital: "Chisinau",                     continent: "Europa" },
  MCO: { name: "Mônaco",           capital: "Mônaco",                       continent: "Europa" },
  MNG: { name: "Mongólia",         capital: "Ulã Bator",                    continent: "Ásia" },
  MNE: { name: "Montenegro",       capital: "Podgorica",                    continent: "Europa" },
  MAR: { name: "Marrocos",         capital: "Rabat",                        continent: "África" },
  MOZ: { name: "Moçambique",       capital: "Maputo",                       continent: "África" },
  MMR: { name: "Mianmar",          capital: "Naypyidaw",                    continent: "Ásia" },
  NAM: { name: "Namíbia",          capital: "Windhoek",                     continent: "África" },
  NPL: { name: "Nepal",            capital: "Catmandu",                     continent: "Ásia" },
  NLD: { name: "Países Baixos",    capital: "Amsterdã",                     continent: "Europa" },
  NZL: { name: "Nova Zelândia",    capital: "Wellington",                   continent: "Oceania" },
  NIC: { name: "Nicarágua",        capital: "Manágua",                      continent: "América do Norte" },
  NER: { name: "Níger",            capital: "Niamey",                       continent: "África" },
  NGA: { name: "Nigéria",          capital: "Abuja",                        continent: "África" },
  MKD: { name: "Macedônia do Norte", capital: "Escópia",                   continent: "Europa" },
  NOR: { name: "Noruega",          capital: "Oslo",                         continent: "Europa" },
  OMN: { name: "Omã",              capital: "Mascate",                      continent: "Ásia" },
  PAK: { name: "Paquistão",        capital: "Islamabad",                    continent: "Ásia" },
  PAN: { name: "Panamá",           capital: "Cidade do Panamá",             continent: "América do Norte" },
  PNG: { name: "Papua-Nova Guiné", capital: "Port Moresby",                 continent: "Oceania" },
  PRY: { name: "Paraguai",         capital: "Assunção",                     continent: "América do Sul" },
  PER: { name: "Peru",             capital: "Lima",                         continent: "América do Sul" },
  PHL: { name: "Filipinas",        capital: "Manila",                       continent: "Ásia" },
  POL: { name: "Polônia",          capital: "Varsóvia",                     continent: "Europa" },
  PRT: { name: "Portugal",         capital: "Lisboa",                       continent: "Europa" },
  QAT: { name: "Catar",            capital: "Doha",                         continent: "Ásia" },
  ROU: { name: "Romênia",          capital: "Bucareste",                    continent: "Europa" },
  RUS: { name: "Rússia",           capital: "Moscou",                       continent: "Europa" },
  RWA: { name: "Ruanda",           capital: "Kigali",                       continent: "África" },
  KNA: { name: "São Cristóvão e Névis", capital: "Basseterre",             continent: "América do Norte" },
  LCA: { name: "Santa Lúcia",      capital: "Castries",                     continent: "América do Norte" },
  VCT: { name: "São Vicente e Granadinas", capital: "Kingstown",            continent: "América do Norte" },
  WSM: { name: "Samoa",            capital: "Apia",                         continent: "Oceania" },
  SMR: { name: "San Marino",       capital: "São Marinho",                  continent: "Europa" },
  STP: { name: "São Tomé e Príncipe", capital: "São Tomé",                  continent: "África" },
  SAU: { name: "Arábia Saudita",   capital: "Riade",                        continent: "Ásia" },
  SEN: { name: "Senegal",          capital: "Dacar",                        continent: "África" },
  SRB: { name: "Sérvia",           capital: "Belgrado",                     continent: "Europa" },
  SYC: { name: "Seicheles",        capital: "Victoria",                     continent: "África" },
  SLE: { name: "Serra Leoa",       capital: "Freetown",                     continent: "África" },
  SGP: { name: "Singapura",        capital: "Singapura",                    continent: "Ásia" },
  SVK: { name: "Eslováquia",       capital: "Bratislava",                   continent: "Europa" },
  SVN: { name: "Eslovênia",        capital: "Liubliana",                    continent: "Europa" },
  SLB: { name: "Ilhas Salomão",    capital: "Honiara",                      continent: "Oceania" },
  SOM: { name: "Somália",          capital: "Mogadíscio",                   continent: "África" },
  ZAF: { name: "África do Sul",    capital: "Pretória",                     continent: "África" },
  SSD: { name: "Sudão do Sul",     capital: "Juba",                         continent: "África" },
  ESP: { name: "Espanha",          capital: "Madri",                        continent: "Europa" },
  LKA: { name: "Sri Lanka",        capital: "Colombo",                      continent: "Ásia" },
  SDN: { name: "Sudão",            capital: "Cartum",                       continent: "África" },
  SUR: { name: "Suriname",         capital: "Paramaribo",                   continent: "América do Sul" },
  SWE: { name: "Suécia",           capital: "Estocolmo",                    continent: "Europa" },
  CHE: { name: "Suíça",            capital: "Berna",                        continent: "Europa" },
  SYR: { name: "Síria",            capital: "Damasco",                      continent: "Ásia" },
  TJK: { name: "Tajiquistão",      capital: "Duchambé",                     continent: "Ásia" },
  TZA: { name: "Tanzânia",         capital: "Dodoma",                       continent: "África" },
  THA: { name: "Tailândia",        capital: "Bangkok",                      continent: "Ásia" },
  TLS: { name: "Timor-Leste",      capital: "Díli",                         continent: "Ásia" },
  TGO: { name: "Togo",             capital: "Lomé",                         continent: "África" },
  TON: { name: "Tonga",            capital: "Nucualofa",                    continent: "Oceania" },
  TTO: { name: "Trinidad e Tobago", capital: "Porto de Espanha",            continent: "América do Norte" },
  TUN: { name: "Tunísia",          capital: "Túnis",                        continent: "África" },
  TUR: { name: "Turquia",          capital: "Ancara",                       continent: "Ásia" },
  TKM: { name: "Turcomenistão",    capital: "Asgabate",                     continent: "Ásia" },
  TUV: { name: "Tuvalu",           capital: "Funafuti",                     continent: "Oceania" },
  UGA: { name: "Uganda",           capital: "Kampala",                      continent: "África" },
  UKR: { name: "Ucrânia",          capital: "Kiev",                         continent: "Europa" },
  ARE: { name: "Emirados Árabes Unidos", capital: "Abu Dhabi",              continent: "Ásia" },
  GBR: { name: "Reino Unido",      capital: "Londres",                      continent: "Europa" },
  USA: { name: "Estados Unidos",   capital: "Washington, D.C.",             continent: "América do Norte" },
  URY: { name: "Uruguai",          capital: "Montevidéu",                   continent: "América do Sul" },
  UZB: { name: "Uzbequistão",      capital: "Tashkent",                     continent: "Ásia" },
  VUT: { name: "Vanuatu",          capital: "Porto Vila",                   continent: "Oceania" },
  VAT: { name: "Vaticano",         capital: "Vaticano",                     continent: "Europa" },
  VEN: { name: "Venezuela",        capital: "Caracas",                      continent: "América do Sul" },
  VNM: { name: "Vietnã",           capital: "Hanói",                        continent: "Ásia" },
  YEM: { name: "Iêmen",            capital: "Saná",                         continent: "Ásia" },
  ZMB: { name: "Zâmbia",           capital: "Lusaka",                       continent: "África" },
  ZWE: { name: "Zimbábue",         capital: "Harare",                       continent: "África" },
  PSE: { name: "Palestina",        capital: "Ramala",                       continent: "Ásia" },
  TWN: { name: "Taiwan",           capital: "Taipé",                        continent: "Ásia" },
  HKG: { name: "Hong Kong",        capital: "Hong Kong",                    continent: "Ásia" },
  XKX: { name: "Kosovo",           capital: "Pristina",                     continent: "Europa" },
};

export function getCountryMeta(iso: string): CountryMeta {
  return COUNTRY_META[iso] ?? { capital: "—", continent: "—" };
}

// ─── Estados brasileiros ──────────────────────────────────────────────────────

export type StateMeta = { capital: string; regiao: string };

export const BRAZIL_STATES: Record<string, StateMeta> = {
  AC: { capital: "Rio Branco",       regiao: "Norte" },
  AL: { capital: "Maceió",           regiao: "Nordeste" },
  AM: { capital: "Manaus",           regiao: "Norte" },
  AP: { capital: "Macapá",           regiao: "Norte" },
  BA: { capital: "Salvador",         regiao: "Nordeste" },
  CE: { capital: "Fortaleza",        regiao: "Nordeste" },
  DF: { capital: "Brasília",         regiao: "Centro-Oeste" },
  ES: { capital: "Vitória",          regiao: "Sudeste" },
  GO: { capital: "Goiânia",          regiao: "Centro-Oeste" },
  MA: { capital: "São Luís",         regiao: "Nordeste" },
  MG: { capital: "Belo Horizonte",   regiao: "Sudeste" },
  MS: { capital: "Campo Grande",     regiao: "Centro-Oeste" },
  MT: { capital: "Cuiabá",           regiao: "Centro-Oeste" },
  PA: { capital: "Belém",            regiao: "Norte" },
  PB: { capital: "João Pessoa",      regiao: "Nordeste" },
  PE: { capital: "Recife",           regiao: "Nordeste" },
  PI: { capital: "Teresina",         regiao: "Nordeste" },
  PR: { capital: "Curitiba",         regiao: "Sul" },
  RJ: { capital: "Rio de Janeiro",   regiao: "Sudeste" },
  RN: { capital: "Natal",            regiao: "Nordeste" },
  RO: { capital: "Porto Velho",      regiao: "Norte" },
  RR: { capital: "Boa Vista",        regiao: "Norte" },
  RS: { capital: "Porto Alegre",     regiao: "Sul" },
  SC: { capital: "Florianópolis",    regiao: "Sul" },
  SE: { capital: "Aracaju",          regiao: "Nordeste" },
  SP: { capital: "São Paulo",        regiao: "Sudeste" },
  TO: { capital: "Palmas",           regiao: "Norte" },
};

export function getStateMeta(uf: string): StateMeta {
  return BRAZIL_STATES[uf] ?? { capital: "—", regiao: "—" };
}
